// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shoeCollection;

namespace shoeCollection.Migrations
{
    [DbContext(typeof(ShoeContext))]
    [Migration("20190330214749_FistMigration")]
    partial class FistMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("shoeCollection.Models.ShoeType", b =>
                {
                    b.Property<int>("ShoeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShoeTypeName");

                    b.HasKey("ShoeTypeId");

                    b.ToTable("ShoeTypes");

                    b.HasData(
                        new { ShoeTypeId = 1, ShoeTypeName = "Basketball" },
                        new { ShoeTypeId = 2, ShoeTypeName = "Casual" },
                        new { ShoeTypeId = 3, ShoeTypeName = "Cross-trainer" },
                        new { ShoeTypeId = 4, ShoeTypeName = "Running" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
